mutation PublishPost($input: PublishPostInput!) {
  publishPost(input: $input) {
    post {
      slug
      title
      content {
        markdown
      }
      publishedAt
      preferences {
        isDelisted
      }
    }
  }
}